id: P004331
initial_creation_type: ocr
source_metadata:
  id: bdr:W3MS471
  title: འཇམ་དབྱངས་བཞད་པའི་རྡོ་རྗེ་བློ་བཟང་ཐུབ་བསྟན་འཇིགས་མེད་རྒྱ་མཚོའི་རྣམ་པར་ཐར།
  author: ''
  volumes:
    4b211f09381b49e9bf1c06cbaa9423ee:
      image_group_id: I3MS473
      title: ''
      volume_number: 1
      total_pages: 413
