id: P004331
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:11:29.050965
source_metadata:
  id: bdr:W3MS471
  title: འཇམ་དབྱངས་བཞད་པའི་རྡོ་རྗེ་བློ་བཟང་ཐུབ་བསྟན་འཇིགས་མེད་རྒྱ་མཚོའི་རྣམ་པར་ཐར།
  author: ''
  volumes:
    4b211f09381b49e9bf1c06cbaa9423ee:
      image_group_id: I3MS473
      title: ''
      volume_number: 1
      total_pages: 413
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
