id: IC77AF1BC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:58:49+00:00'
last_modified: '2022-06-07T22:03:10.274439+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3MS471
  title: འཇམ་དབྱངས་བཞད་པའི་རྡོ་རྗེ་བློ་བཟང་ཐུབ་བསྟན་འཇིགས་མེད་རྒྱ་མཚོའི་རྣམ་པར་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0E70:
      image_group_id: I3MS473
      title: ''
      total_pages: 413
      order: 1
      base_file: 0E70.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
